version: '3'

services:
  backend:
    build:
      context: .  
      dockerfile: Backend/Dockerfile  
    ports:
      - "8000:8000"  
    volumes:
      - ./Backend:/app  
    environment:
      - NODE_ENV=production  
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]  

  frontend:
    build:
      context: .  
      dockerfile: Frontend/Dockerfile 
    ports:
      - "3000:3000"  
    volumes:
      - ./Frontend:/app  
    mem_limit: 2g  
    environment:
      - NODE_ENV=development  
    working_dir: /app/src  
    command: ["npm", "start"]  
